language: r
cache: packages
warnings_are_errors: false
r:
  - 3.4

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 4"

r_packages:
  - covr

after_success:
- Rscript -e 'covr::codecov()'
