language: r
cache: packages
latex: false
warnings_are_errors: false

jobs:
  include:
    - r: 3.5

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
